name: polish version

on:
  workflow_dispatch:
  push:
    branches: [ polish-version ]
  pull_request:
    branches: [ polish-version ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build
      run: |
           cd ./accessibility-checker-extension
           npm install shx
           npm run clean:all
           npm install
           npm run package:browser
    - name: Upload archive
      uses: actions/upload-artifact@v2
      with:
          name: polish-version
          path: |
            ./accessibility-checker-extension/package/accessibility-checker-extension.zip
